server.port=8080
spring.application.name=api-gateway

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.main.web-application-type=reactive

# ================= PRODUCT SERVICE =================
spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=lb://product-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/products/**

# ================= CATEGORY / BRAND / SUPPLIER (same service) =================
spring.cloud.gateway.routes[1].id=product-service-others
spring.cloud.gateway.routes[1].uri=lb://product-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/categories/**,/api/brands/**,/api/suppliers/**

# ================= CUSTOMER SERVICE =================
spring.cloud.gateway.routes[2].id=customer-service
spring.cloud.gateway.routes[2].uri=lb://customer-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/customers/**

# ================= ORDER SERVICE =================
spring.cloud.gateway.routes[3].id=order-service
spring.cloud.gateway.routes[3].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/orders/**

# ================= INVENTORY (ADDED) =================
spring.cloud.gateway.routes[4].id=inventory-service
spring.cloud.gateway.routes[4].uri=lb://product-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/inventory/**